### ISSUE TITLE
Composer Package Out Of Date

### ISSUE THREAD

**Issue by Tilogorn** [singpolyma/openpgp-php#86]
The latest release on Composer is version 0.3.0, released on  12 Apr 2017. Is the concept of tagging releases and uploading them to Packagist dead in this project?

It would just be good to know, so that I can manage my dependencies accordingly.

**Comment by singpolyma** [comment]
I have pushed a 0.4.0 tag of current master.

**Comment by Tilogorn** [comment]
Nice to hear. Is this like an official and tested release? I didn't open this issue just to get the current master on Composer (I could clone the repo for that). No offense, I'm just curious. We use your code in production...

**Comment by singpolyma** [comment]
>I didn't open this issue just to get the current master on Composer

So far all tags of this package have been by user demand.  The library is 
still pre-1.0 so every release may have breaking changes, and so far I 
haven't been writing changelogs for pre-1.0 either here.  Most changes since 
the last release are pretty minimal in this case, though the commit list is 
small enough you could look if you're wondering without much pain.

I endeavour to keep master always passing CI, and of course the release 
passes CI.

So this release is as "official" as any of them have been.  If there are 
specific kinds of rigour (like me actually writing a changelog) you would 
like to see for future releases, I'm happy to consider them.
